/* AUTO-GENERATED by build.rs from src/. Do not edit by hand. */

#ifndef ADVENTERM_FFI_H
#define ADVENTERM_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Sentinel value written into [`CEquipmentSnapshot`] slot fields when the
 * slot is empty. `255` is unreachable as an `ItemKind` discriminant for the
 * foreseeable future (the lib has 8 variants).
 */
#define C_EQUIPMENT_SLOT_EMPTY UINT8_MAX

/**
 * Independent owner of a [`Battle`]. Does not borrow from a [`GameHandle`];
 * the snapshot it carries is cloned at construction.
 */
typedef struct BattleHandle BattleHandle;

/**
 * Independent owner of a [`ConsoleState`].
 *
 * `inner` mirrors what the binary owns: input buffer, cursor, completion
 * view. `history` is FFI-side because the lib's history is private (no
 * public accessor); we maintain our own log of submitted prompts so the
 * `console_history_*` exports can satisfy Pattern C.
 */
typedef struct ConsoleHandle ConsoleHandle;

/**
 * Root handle: owns a [`GameState`].
 */
typedef struct GameHandle GameHandle;

/**
 * Independent owner of a [`Save`].
 */
typedef struct SaveHandle SaveHandle;

/**
 * Listing of saves in a directory.
 */
typedef struct SaveListing SaveListing;

typedef struct CCombatants {
  uint32_t enemy_entity;
  uint32_t enemy_room;
} CCombatants;

typedef struct CHpSnapshot {
  uint8_t player;
  uint8_t enemy;
} CHpSnapshot;

typedef struct CBattleTurn {
  /**
   * 0 = Player, 1 = Enemy, 2 = Resolved.
   */
  uint8_t tag;
  /**
   * Valid iff `tag == 2`. Otherwise `0`. Holds a [`CBattleResult`].
   */
  uint8_t result;
  uint8_t _pad[2];
} CBattleTurn;

typedef struct CStats {
  uint8_t health;
  uint8_t attack;
  uint8_t defense;
  uint8_t speed;
  /**
   * [`CAttribute`] discriminant.
   */
  uint8_t attribute;
} CStats;

typedef struct CConsumeTarget {
  /**
   * 0 = None, 1 = AbilitySlot.
   */
  uint8_t tag;
  uint8_t _pad[3];
  /**
   * Valid iff `tag == 1`. Otherwise `0`.
   */
  uint32_t slot;
} CConsumeTarget;

typedef struct CConsumeOutcome {
  /**
   * 0 = Used (no payload), 1 = LearnedAbility (payload valid).
   */
  uint8_t tag;
  /**
   * [`CAbilityKind`] discriminant when `tag == 1`. Otherwise `0`.
   */
  uint8_t kind;
  uint8_t _pad[2];
  /**
   * Active-ability slot when `tag == 1`. Otherwise `0`.
   */
  uint32_t slot;
} CConsumeOutcome;

typedef struct CDoorEvent {
  uint32_t from;
  uint32_t to;
  uint32_t new_room;
} CDoorEvent;

typedef struct CMoveOutcome {
  /**
   * 0 = Blocked, 1 = Moved, 2 = Encounter.
   */
  uint8_t tag;
  uint8_t _pad[3];
  /**
   * Valid iff `tag == 2`. Otherwise `0`.
   */
  uint32_t encounter_entity;
} CMoveOutcome;

typedef struct CEquipmentSnapshot {
  /**
   * Each field is [`C_EQUIPMENT_SLOT_EMPTY`] when empty, or a
   * [`CItemKind`] discriminant otherwise.
   */
  uint8_t head;
  uint8_t torso;
  uint8_t arms;
  uint8_t legs;
  uint8_t feet;
} CEquipmentSnapshot;

typedef struct CTileKind {
  /**
   * 0 = Wall, 1 = Floor, 2 = Door.
   */
  uint8_t tag;
  uint8_t _pad[3];
  /**
   * Valid iff `tag == 2`. Otherwise `0`.
   */
  uint32_t door_id;
} CTileKind;

typedef struct CDoorView {
  uint32_t door_id;
  /**
   * [`CDoorState`] discriminant.
   */
  uint8_t state;
  uint8_t _pad[3];
  uint32_t from_room;
  uint32_t to_room;
  uint32_t x;
  uint32_t y;
} CDoorView;

typedef struct CEnemyView {
  uint32_t entity;
  /**
   * [`CEnemyKind`] discriminant.
   */
  uint8_t kind;
  uint8_t _pad[3];
  uint32_t x;
  uint32_t y;
} CEnemyView;

typedef struct CFlareSource {
  uint32_t entity;
  uint32_t x;
  uint32_t y;
} CFlareSource;

typedef struct CLightSource {
  uint32_t entity;
  uint32_t x;
  uint32_t y;
  uint8_t radius;
  uint8_t _pad[3];
} CLightSource;

const char *ability_kind_name(uint8_t kind);

const char *attribute_name(uint8_t attr);

int32_t battle_apply_enemy_turn(const struct GameHandle *game, struct BattleHandle *battle);

int32_t battle_apply_player_ability(const struct GameHandle *game,
                                    struct BattleHandle *battle,
                                    uintptr_t ability_slot);

int32_t battle_combatants(const struct BattleHandle *battle, struct CCombatants *out_combatants);

int32_t battle_enemy_cur_hp(const struct BattleHandle *battle, uint8_t *out_hp);

/**
 * Free a handle previously returned by [`battle_start`]. Null is a no-op.
 */
void battle_free(struct BattleHandle *battle);

int32_t battle_hp_snapshot(const struct BattleHandle *battle, struct CHpSnapshot *out_hp);

int32_t battle_is_resolved(const struct BattleHandle *battle, bool *out);

/**
 * Two-call discovery copy of log line `index` into a caller-allocated
 * buffer. With `buf == null` (or `cap` smaller than the required size),
 * returns [`FfiError::BufferTooSmall`] after writing the needed byte count
 * (including the trailing NUL) into `out_required`.
 */
int32_t battle_log_line_copy(const struct BattleHandle *battle,
                             uintptr_t index,
                             uint8_t *buf,
                             uintptr_t cap,
                             uintptr_t *out_required);

int32_t battle_log_line_count(const struct BattleHandle *battle, uintptr_t *out_count);

int32_t battle_player_cur_hp(const struct BattleHandle *battle, uint8_t *out_hp);

/**
 * Read the terminal result. `out_has_result` is true only when the battle
 * is resolved; otherwise `out_result` is left at zero and callers should
 * ignore it.
 */
int32_t battle_result(const struct BattleHandle *battle, uint8_t *out_result, bool *out_has_result);

/**
 * Try to construct a [`BattleHandle`] for `enemy_entity` in `game`'s current
 * room. Writes the new handle and `out_started=true` on success. When the
 * engine declines (no such enemy in the current room), writes `null` and
 * `out_started=false` and returns `Ok` — the spec models "no battle could
 * start" as a successful outcome, not an error.
 */
int32_t battle_start(const struct GameHandle *game,
                     uint32_t enemy_entity,
                     struct BattleHandle **out_battle,
                     bool *out_started);

int32_t battle_turn(const struct BattleHandle *battle, struct CBattleTurn *out_turn);

int32_t console_clear(struct ConsoleHandle *console);

int32_t console_command_count(uintptr_t *out_count);

int32_t console_command_help(uintptr_t index, uint8_t *buf, uintptr_t cap, uintptr_t *out_required);

int32_t console_command_name(uintptr_t index, uint8_t *buf, uintptr_t cap, uintptr_t *out_required);

/**
 * Recompute the cached completion view from the current input. `game` may
 * be null — completion candidates that consult game state simply receive
 * `None` for the [`CompletionCtx`], matching the lib's contract.
 */
int32_t console_complete(struct ConsoleHandle *console, const struct GameHandle *game);

int32_t console_completion_at(const struct ConsoleHandle *console,
                              uintptr_t index,
                              uint8_t *buf,
                              uintptr_t cap,
                              uintptr_t *out_required);

int32_t console_completion_count(const struct ConsoleHandle *console, uintptr_t *out_count);

int32_t console_cursor(const struct ConsoleHandle *console, uintptr_t *out_pos);

int32_t console_delete_back(struct ConsoleHandle *console);

/**
 * Free a handle previously returned by [`console_new`]. Null is a no-op.
 */
void console_free(struct ConsoleHandle *console);

int32_t console_history_count(const struct ConsoleHandle *console, uintptr_t *out_count);

int32_t console_history_line_copy(const struct ConsoleHandle *console,
                                  uintptr_t index,
                                  uint8_t *buf,
                                  uintptr_t cap,
                                  uintptr_t *out_required);

int32_t console_input_get(const struct ConsoleHandle *console,
                          uint8_t *buf,
                          uintptr_t cap,
                          uintptr_t *out_required);

int32_t console_input_set(struct ConsoleHandle *console, const char *text);

/**
 * Insert one Unicode scalar at the caret. Invalid scalar values (surrogates,
 * out-of-range) return [`FfiError::OutOfRange`].
 */
int32_t console_insert_char(struct ConsoleHandle *console, uint32_t codepoint);

/**
 * Construct a fresh console handle. Writes the new pointer to `out_console`.
 */
int32_t console_new(struct ConsoleHandle **out_console);

/**
 * Set the caret to `pos`. Out-of-range or non-char-boundary positions
 * return [`FfiError::OutOfRange`] with detail in `LAST_ERROR`.
 */
int32_t console_set_cursor(struct ConsoleHandle *console, uintptr_t pos);

/**
 * Run the command currently in the input buffer. Mirrors the lib's
 * `ConsoleState::submit` flow but captures the executed command's
 * `Result<String, String>` into the caller's buffer instead of routing it
 * through the `log` crate. `out_was_error` is set when the user typed an
 * unknown command or the matched command returned `Err`.
 */
int32_t console_submit(struct ConsoleHandle *console,
                       struct GameHandle *game,
                       uint8_t *out_response,
                       uintptr_t cap,
                       uintptr_t *out_required,
                       bool *out_was_error);

int32_t enemy_kind_base_stats(uint8_t kind, struct CStats *out_stats);

int32_t enemy_kind_glyph(uint8_t kind, uint32_t *out_glyph);

const char *enemy_kind_name(uint8_t kind);

const char *equip_slot_name(uint8_t slot);

/**
 * Pointer to the current thread's last error detail, or null when none is
 * set. The pointer is valid until the next FFI call on this thread; callers
 * that need the message past that point must copy it immediately.
 */
const char *ffi_last_error_message(void);

int32_t game_abilities_active_copy(const struct GameHandle *handle,
                                   uint8_t *out_buf,
                                   uintptr_t cap,
                                   uintptr_t *out_required);

int32_t game_abilities_learned_active_copy(const struct GameHandle *handle,
                                           uint8_t *out_buf,
                                           uintptr_t cap,
                                           uintptr_t *out_required);

int32_t game_abilities_learned_active_len(const struct GameHandle *handle, uintptr_t *out_len);

int32_t game_abilities_learned_passive_copy(const struct GameHandle *handle,
                                            uint8_t *out_buf,
                                            uintptr_t cap,
                                            uintptr_t *out_required);

int32_t game_abilities_learned_passive_len(const struct GameHandle *handle, uintptr_t *out_len);

int32_t game_abilities_passive_copy(const struct GameHandle *handle,
                                    uint8_t *out_buf,
                                    uintptr_t cap,
                                    uintptr_t *out_required);

int32_t game_action_consume(struct GameHandle *handle,
                            uintptr_t inventory_slot,
                            struct CConsumeTarget target,
                            struct CConsumeOutcome *out_outcome,
                            bool *out_has_outcome);

int32_t game_action_defeat_enemy(struct GameHandle *handle, uint32_t room, uint32_t entity);

int32_t game_action_equip(struct GameHandle *handle,
                          uintptr_t inventory_slot,
                          uint8_t *out_unequipped_kind,
                          bool *out_has_unequipped);

int32_t game_action_interact(struct GameHandle *handle,
                             struct CDoorEvent *out_door_event,
                             bool *out_has_event);

int32_t game_action_move(struct GameHandle *handle,
                         uint8_t direction,
                         struct CMoveOutcome *out_outcome);

int32_t game_action_pickup(struct GameHandle *handle,
                           uint8_t *out_picked_kind,
                           bool *out_has_pickup);

int32_t game_action_place(struct GameHandle *handle,
                          uintptr_t inventory_slot,
                          uint8_t *out_outcome,
                          bool *out_has_outcome);

int32_t game_action_quick_move(struct GameHandle *handle,
                               uint8_t direction,
                               struct CMoveOutcome *out_outcome);

int32_t game_action_unequip(struct GameHandle *handle, uint8_t equip_slot, bool *out_success);

int32_t game_cur_health(const struct GameHandle *handle, uint8_t *out_hp);

int32_t game_current_room(const struct GameHandle *handle, uint32_t *out_room);

int32_t game_effective_stats(const struct GameHandle *handle, struct CStats *out_stats);

int32_t game_equipment_snapshot(const struct GameHandle *handle, struct CEquipmentSnapshot *out);

/**
 * Free a handle previously returned by [`game_new_seeded`]. A null pointer
 * is a no-op (matches C's `free(NULL)` convention).
 */
void game_free(struct GameHandle *handle);

int32_t game_fullbright(const struct GameHandle *handle, bool *out);

int32_t game_inventory_copy(const struct GameHandle *handle,
                            uint8_t *out_buf,
                            uintptr_t cap,
                            uintptr_t *out_required);

int32_t game_inventory_len(const struct GameHandle *handle, uintptr_t *out_len);

int32_t game_is_explored(const struct GameHandle *handle, uintptr_t x, uintptr_t y, bool *out);

int32_t game_is_visible(const struct GameHandle *handle, uintptr_t x, uintptr_t y, bool *out);

int32_t game_items_here(const struct GameHandle *handle, bool *out);

/**
 * Construct a fresh game from `seed`. Returns a non-null handle on success;
 * pair every successful call with exactly one [`game_free`].
 */
struct GameHandle *game_new_seeded(uint64_t seed);

int32_t game_peek_item_here(const struct GameHandle *handle, uint8_t *out_kind, bool *out_has_item);

int32_t game_pending_encounter(const struct GameHandle *handle,
                               uint32_t *out_entity,
                               bool *out_has_encounter);

int32_t game_player_on_door(const struct GameHandle *handle,
                            uint32_t *out_door_id,
                            bool *out_has_door);

int32_t game_player_pos(const struct GameHandle *handle, uintptr_t *out_x, uintptr_t *out_y);

int32_t game_refresh_visibility(struct GameHandle *handle);

int32_t game_room_dimensions(const struct GameHandle *handle,
                             uint32_t room,
                             uintptr_t *out_width,
                             uintptr_t *out_height);

int32_t game_room_kind_at(const struct GameHandle *handle,
                          uint32_t room,
                          uintptr_t x,
                          uintptr_t y,
                          struct CTileKind *out_kind);

int32_t game_room_walkable(const struct GameHandle *handle,
                           uint32_t room,
                           uintptr_t x,
                           uintptr_t y,
                           bool *out);

int32_t game_set_cur_health(struct GameHandle *handle, uint8_t hp);

int32_t game_set_fullbright(struct GameHandle *handle, bool on);

int32_t game_set_pending_encounter(struct GameHandle *handle, uint32_t entity);

int32_t game_take_pending_encounter(struct GameHandle *handle,
                                    uint32_t *out_entity,
                                    bool *out_has_encounter);

int32_t game_terrain_at(const struct GameHandle *handle,
                        uintptr_t x,
                        uintptr_t y,
                        uint8_t *out_tile);

int32_t game_tile_at(const struct GameHandle *handle, uintptr_t x, uintptr_t y, uint8_t *out_tile);

int32_t game_vision_radius(const struct GameHandle *handle, uintptr_t *out_radius);

int32_t item_kind_glyph(uint8_t kind, uint32_t *out_glyph);

const char *item_kind_name(uint8_t kind);

int32_t room_door_at(const struct GameHandle *handle, uintptr_t index, struct CDoorView *out_view);

int32_t room_doors_count(const struct GameHandle *handle, uintptr_t *out_count);

int32_t room_enemies_count(const struct GameHandle *handle, uint32_t room, uintptr_t *out_count);

int32_t room_enemy_at(const struct GameHandle *handle,
                      uint32_t room,
                      uintptr_t index,
                      struct CEnemyView *out_view);

int32_t room_flare_at(const struct GameHandle *handle,
                      uintptr_t index,
                      struct CFlareSource *out_view);

int32_t room_flares_count(const struct GameHandle *handle, uintptr_t *out_count);

int32_t room_item_at(const struct GameHandle *handle,
                     uintptr_t x,
                     uintptr_t y,
                     uintptr_t index,
                     uint8_t *out_kind);

int32_t room_items_at_count(const struct GameHandle *handle,
                            uintptr_t x,
                            uintptr_t y,
                            uintptr_t *out_count);

int32_t room_light_at(const struct GameHandle *handle,
                      uintptr_t index,
                      struct CLightSource *out_view);

int32_t room_lights_count(const struct GameHandle *handle, uintptr_t *out_count);

int32_t save_delete(const char *path);

uint32_t save_format_version(void);

void save_free(struct SaveHandle *save);

int32_t save_from_bytes(const uint8_t *bytes, uintptr_t len, struct SaveHandle **out_save);

int32_t save_list_count(const struct SaveListing *listing, uintptr_t *out_count);

void save_list_free(struct SaveListing *listing);

int32_t save_list_modified_unix(const struct SaveListing *listing,
                                uintptr_t index,
                                int64_t *out_unix_seconds);

int32_t save_list_name(const struct SaveListing *listing,
                       uintptr_t index,
                       uint8_t *buf,
                       uintptr_t cap,
                       uintptr_t *out_required);

int32_t save_list_open(const char *dir, struct SaveListing **out_listing);

int32_t save_list_path(const struct SaveListing *listing,
                       uintptr_t index,
                       uint8_t *buf,
                       uintptr_t cap,
                       uintptr_t *out_required);

int32_t save_name(const struct SaveHandle *save,
                  uint8_t *buf,
                  uintptr_t cap,
                  uintptr_t *out_required);

int32_t save_new_from_game(const struct GameHandle *handle,
                           const char *name,
                           struct SaveHandle **out_save);

int32_t save_slot_path(const char *dir,
                       const char *name,
                       uint8_t *buf,
                       uintptr_t cap,
                       uintptr_t *out_required);

int32_t save_slugify(const char *name, uint8_t *buf, uintptr_t cap, uintptr_t *out_required);

int32_t save_to_bytes(const struct SaveHandle *save,
                      uint8_t *buf,
                      uintptr_t cap,
                      uintptr_t *out_required);

int32_t save_to_game(const struct SaveHandle *save, struct GameHandle **out_game);

int32_t save_version(const struct SaveHandle *save, uint32_t *out_version);

#endif  /* ADVENTERM_FFI_H */
